version: '3'

services: 
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
     
       
       MYSQL_DATABASE: 'budemi'
       MYSQL_USER: "admin"
       MYSQL_PASSWORD: '12345'
       MYSQL_ALLOW_EMPTY_PASSWORD: "True"
       
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql

  web:
    
    build: .
    command:
      - /bin/sh
      - -c
      - |
          echo "sleep for 10sec"
          sleep 10 
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
          
          
    
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db 