version: '3'
services:
  web:
    build: .
    command: python practiceapp/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=django_prod
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=learningManagement
      - MYSQL_ROOT_PASSWORD=learningManagement
      - MYSQL_HOST=djangodb.cuonjdhh9ksf.us-east-1.rds.amazonaws.com
      - teacher_course_statistics_api=e5e0aa9024mshdbd00e1fc1a3f31p14545ejsn9af52ee101e7
      - RandomUsername_API_KEY=768d5c5ca7msh0de1bf3500804cbp1b12f3jsn930da0c69205
      - API_KEY_give_rate=UXzo3fo9cg3c3/V4CF17Jw==o9S0YYHLBairenXf